### ISSUE TITLE
queryString is not being encoded before being sent as get request

### ISSUE THREAD

**Issue by rooberrydev** [fac-17/cgko-week-4#18]
in your index.js file(client side)

queryString is being defined as 
```
let queryString = input.value;
```
and its directly sent to the server in a get request
```
xhr.open("GET", queryString, true);
```

the problem here is that urls only allow certain characters.
forbidden characters must be encoded into their hex equivalents.
(refer to week4 research, I have mentioned url encoding)

there is a convenient method encodeURIComponent() that will take your queryString and encode it in the correct format.

```
let queryString=encodeURIComponent(input.value)
```

**Comment by xIrusux** [comment]
closed thanks :)
