### ISSUE TITLE
Datalist repitition

### ISSUE THREAD

**Issue by sylv1ah** [fac-17/cgko-week-4#20]
Good job using the datalist element!

But you may want to look into clearing it once the input is updated so that it does't keep adding results from previous inputs

**Comment by xIrusux** [comment]
Hi silvia :) 
That's interesting as we thought we fixed that problem. 
I have just tested the app and it looks like the suggestions change everytime I change my input. 
Do you have a screenshot of what you are referring to? 

Thank you very much
