### ISSUE TITLE
Server running message is showed before it starts

### ISSUE THREAD

**Issue by crianonim** [fac-17/cgko-week-4#21]
```
server.listen(port);
console.log(`server up and running on port: ${port}`);
```
At the moment what it does it starts binding the port, then you outputs the message, then it starts the server, which can throw an error, so the message is premature.
Easy fix is to put the message inside the callback:
```
server.listen(port,()=>{
 console.log(`server up and running on port: ${port}`);
});

```

**Comment by xIrusux** [comment]
solved
